-- Schema is maintained as numbered migrations in /migrations/
-- Run each file in order in the Supabase SQL editor.
-- 001 = initial schema
-- 002 = RLS policies
-- 003 = orders table
-- 004 = image_url column
